---
- name: restart supervisor
  shell: service supervisor restart
  sudo: yes

- name: start supervisor
  service: name=supervisor state=started
  sudo: yes

- name: enable supervisor
  service: name=supervisor enabled=yes
  sudo: yes
