#!/bin/bash

# Generates changelog day by day
NEXT=$(date +%F)
echo "History"
echo "----------------------"
echo "<small>Note: This file is autogenerated with [generate-history.sh](generate-history.sh)</small>"
git log --no-merges --format="%cd" --date=short | sort -u -r | while read DATE ; do
    echo
    echo "### $DATE"
    GIT_PAGER=cat git log --no-merges --format=" - %s ([%aN])" --since="$DATE 00:00" --until="$DATE 23:59"
done

echo ""
echo "----------------------"
echo ""
if test -f "AUTHORS.md"; then
    cat AUTHORS.md >> HISTORY.md
fi

