---
- hosts: vagrant
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - postgresql
    - project_data
{%- if cookiecutter.add_celery.lower() == 'y' %}
    - redis
    - celery
{%- else %}
    # - redis
    # - celery
{%- endif %}

#= Dev
#===================================================
- hosts: dev
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - postgresql
    - project_data
{%- if cookiecutter.add_celery.lower() == 'y' %}
    - redis
    - celery
{%- else %}
    # - redis
    # - celery
{%- endif %}

#= QA
#===================================================
- hosts: qa
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - project_data
    - postgresql
{%- if cookiecutter.add_celery.lower() == 'y' %}
    - redis
    - celery
{%- else %}
    # - redis
    # - celery
{%- endif %}

#= Production
#===================================================
- hosts: production
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - project_data
{%- if cookiecutter.add_celery.lower() == 'y' %}
    - redis
    - celery
{%- else %}
    # - redis
    # - celery
{%- endif %}
