---
- name: ensure supervisor is installed
  apt: pkg=supervisor state=installed update-cache=yes

- name: ensure supervisor config dir exists
  file: path=/etc/supervisor state=directory mode=0755 owner=root group=root

- name: ensure supervisor is running
  service: name=supervisor state=started
