---
- hosts: vagrant
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - supervisor
    - postgresql
    - project_data
    - letsencrypt
    # - redis
    # - celery


- hosts: production
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - supervisor
    - project_data
    - letsencrypt
    # - redis
    # - celery
