#!/bin/bash

set -o errexit
set -o nounset


celery \
    -A {{ cookiecutter.main_module }} \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
