image: python:3.5.2
services:
    - postgres:9.4

variables:
    # Configure postgres service
    POSTGRES_DB: {{ cookiecutter.main_module }}
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

lint:
    script:
        - pip install flake8==2.5.4
        - flake8 .

django_app:
    script:
        - apt-get update -qy
        - apt-get install -y python3-dev libpq-dev
        - export DATABASE_URL=postgres://postgres:postgres@postgres/{{ cookiecutter.main_module }}
        - pip install -r requirements/development.txt
        - py.test --cov -v --tb=native

{% if cookiecutter.add_ansible.lower() == 'y' %}
ansible:
    script:
        - pip install ansible
        - ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check
{% endif %}
