version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: {{ cookiecutter.main_module }}_local_django
    container_name: {{ cookiecutter.main_module }}-django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.env
#      - ./.envs/.local/.django
#      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/dev/postgres/Dockerfile
    image: {{ cookiecutter.main_module }}_local_postgres
    container_name: {{ cookiecutter.main_module }}-postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.env
#      - ./.envs/.local/.postgres

  redis:
    image: redis:alpine
    container_name: {{ cookiecutter.main_module }}-redis
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: {{ cookiecutter.main_module }}_local_celeryworker
    container_name: {{ cookiecutter.main_module }}-celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.main_module }}_local_celerybeat
    container_name: {{ cookiecutter.main_module }}-celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.main_module }}_local_flower
    container_name: {{ cookiecutter.main_module }}-flower
    ports:
      - "5555:5555"
    command: /start-flower
