web: {% if cookiecutter.newrelic == 'y' %}newrelic-admin run-program {% endif %}uwsgi uwsgi.ini
{%- if cookiecutter.add_celery == 'y' %}
worker: celery -A dutchess worker -l info --concurrency=2 -B
{%- endif %}
