---
- hosts: vagrant
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true

  roles:
    - common
    - nginx
    - supervisor
    - postgresql
    - project_data
    - gunicorn
    # - redis
    # - celery


- hosts: production
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true

  roles:
    - common
    - nginx
    - supervisor
    - project_data
    - gunicorn
    # - redis
    # - celery
