name: Run tests for {{cookiecutter.main_module}}

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      PGDATABASE=postgres
      PGHOST=localhost
      PGUSER=postgres
      PGPASS=postgres
    {%- if cookiecutter.postgis.lower() == 'y' %}
      DATABASE_URL=postgis://${PGUSER}:${PGPASS}@${PGHOST}:${PGPORT}/${PGDATABASE}
    {%- else %}
      DATABASE_URL=postgres://${PGUSER}:${PGPASS}@${PGHOST}:${PGPORT}/${PGDATABASE}
    {%- endif %}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        pip install -r requirements/development.txt
    - name: Check linting
      run: flake8
    - name: Run tests
      run: |
        pytest --cov -v --tb=native
{% if cookiecutter.add_ansible.lower() == 'y' %}
    - name: Ansible Syntax checks
      run: |
        ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check
{% endif %}

