name: Run tests for {{cookiecutter.main_module}}

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:13-master
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
    {%- if cookiecutter.postgis.lower() == 'y' %}
      DATABASE_URL=postgis://postgres:postgres@localhost:5432/{{cookiecutter.main_module}}
    {%- else %}
      DATABASE_URL=postgres://postgres:postgres@localhost:5432/{{cookiecutter.main_module}}
    {%- endif %}

    steps:
    - uses: actions/checkout@v2
    - name: Install gdal
      run: |
        sudo apt-get install gdal-bin python-gdal
        sudo apt-get install libgdal-dev
        sudo apt-get install postgresql-13-postgis-3-scripts
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        pip install -r requirements/development.txt
    - name: flake8 Lint
      uses: py-actions/flake8@v1
      with:
        exclude: "src/"
        max-line-length: "120"
        path: "."
    - name: Run tests
      run: |
        pytest --cov -v --tb=native
{% if cookiecutter.add_ansible.lower() == 'y' %}
    - name: Ansible Syntax checks
      run: |
        ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check
{% endif %}

