name: Run Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: {% if cookiecutter.add_postgis.lower() == 'y' %}postgis/postgis:13-master{% else %}postgres:13{% endif %}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: {% if cookiecutter.add_postgis.lower() == 'y' %}postgis{% else %}postgres{% endif %}://postgres:postgres@localhost:5432/{{cookiecutter.main_module}}

    steps:
    - uses: actions/checkout@v2
    {%- if cookiecutter.add_postgis.lower() == 'y' %}
    - name: Install gdal
      run: |
        sudo apt-get install gdal-bin
        sudo apt-get install libgdal-dev
        # Update is essential for fetching postgis-3 scripts
        sudo apt-get update
        sudo apt-get install postgresql-13-postgis-3-scripts
    {%- endif %}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements/development.txt
    - name: Run tests
      run: |
        pytest --cov -v --tb=native
    - name: Linting
      run: |
        make lint
